apiVersion: stackpulse.io/v1
kind: Playbook
metadata:
  description: Kubernetes label logs
  name: kubernetes-label-logs
parameters:
  - name: namespace
    type: var
    description: The relevant namespace to operate
    default: "default"
    example: "default"
    required: false
  - name: label
    type: var
    description: The relevant entity to operate on
    required: false
  - name: KubernetesIntegration
    type: integration
    description: Kubernetes integration name
    options:
      integration_type: k8s
steps:
  - name: us-docker.pkg.dev/stackpulse/public/kubectl/logs
    id: kubectl_cmd
    env:
      LABEL: "{{ $.params.label }}"
      NAMESPACE: "{{ $.params.namespace }}"
    envFrom:
      integrationRef: "{{ $.params.KubernetesIntegration }}"