apiVersion: stackpulse.io/v1
kind: Playbook
metadata:
  description: Kubernetes playbook to operate deletion for given pod
  name: kubernetes-delete-pod
parameters:
  - name: namespace
    type: var
    description: The relevant namespace to operate
  - name: entity
    type: var
    description: The relevant entity to operate on
  - name: KubernetesIntegration
    type: integration
    description: Kubernetes integration name
    options:
      integration_type: k8s
steps:
  - name: us-docker.pkg.dev/stackpulse/public/kubectl/delete
    id: kubectl_cmd
    env:
      RESOURCE_TYPE: "pod"
      RESOURCES_NAMES: "{{ $.params.entity }}"
      NAMESPACE: "{{ $.params.namespace }}"
    envFrom:
      integrationRef: "{{ $.params.KubernetesIntegration }}"
