apiVersion: stackpulse.io/v1
kind: Playbook
metadata:
  name: job-failed
  description: Handle failed kubernetes job by sending the logs of its pods via slack, and  delete or reruns it according to the user selection.
parameters:
  - name: runner
    type: spd
    description: Name of target cluster spd.
  - name: namespace
    type: var
    description: Kubernetes jobs namespace.
  - name: job_name
    type: var
    Description: Name of the specific job that failed. usually in this structure - <cronjob
      name>-<number>.
  - name: recipient
    type: var
    description: Email of slack recipient, or a channel name prefixed with
    default: "{{ $.metadata.userEmail }}"
  - name: slack_integration
    type: integration
    description: Slack integration.
    options:
      integration_type: slack
steps:
  - name: us-docker.pkg.dev/stackpulse/public/kubectl/get-pods
    id: get_pods
    runner: "{{ $.params.runner }}"
    env:
      NAMESPACE: "{{ $.params.namespace }}"
      NAME_CONTAINS: "{{ $.params.job_name }}"
      FIELD_SELECTOR: status.phase=Failed
  - foreach:
      in: filtered
      key: key
      value: value
      steps:
        - name: us-docker.pkg.dev/stackpulse/public/kubectl/logs
          runner: "{{ $.params.runner }}"
          env:
            NAMESPACE: "{{ $.params.namespace }}"
            POD_NAME: "{{ .value.name }}"
            SP_FORMATTER: raw
            ALL_CONTAINERS: "true"
        - name: us-docker.pkg.dev/stackpulse/public/slack/message/snippet
          envFrom:
            integrationRef: "{{ $.params.slack_integration }}"
          env:
            CONTENT: "{{ $.output }}"
            RECIPIENTS: "{{ $.params.recipient }}"
            SP_REDIRECT_URL: "{{ $.metadata.executionUrl }}"
  - name: us-docker.pkg.dev/stackpulse/public/slack/message/interactive
    id: ask_which_action
    envFrom:
      integrationRef: "{{ $.params.slack_integration }}"
    env:
      SP_REDIRECT_URL: "{{ $.metadata.executionUrl }}"
      HEADER_MESSAGE: Hello developer,
      RECIPIENTS: "{{ $.params.recipient }}"
      QUESTION: The job {{ $.params.job_name }} has failed. What whould you like to do?
      RESPONSES: Rerun,Delete,Nothing
      SELECTOR_TYPE: BUTTONS_SELECT
      TIMEOUT: 5m
      DEFAULT_RESPONSE: 'Delete'
  - when: '{{ eq $.ask_which_action.slack_response "Delete" }}'
    steps:
      - name: us-docker.pkg.dev/stackpulse/public/kubectl/delete
        runner: "{{ $.params.runner }}"
        id: kubectl_delete
        env:
          RESOURCE_TYPE: job
          RESOURCES_NAMES: "{{ $.params.job_name }}"
      - name: us-docker.pkg.dev/stackpulse/public/slack/message/dynamic
        id: slack_send_dynamic_message
        envFrom:
          integrationRef: "{{ $.params.slack_integration }}"
        env:
          RECIPIENTS: "{{ $.params.recipient }}"
          MESSAGE_TEXT: Job {{ $.params.job_name }} was succesfully deleted!
          SP_REDIRECT_URL: "{{ $.metadata.executionUrl }}"
  - when: '{{ eq $.ask_which_action.slack_response "Rerun" }}'
    steps:
      - name: us-docker.pkg.dev/stackpulse/public/kubectl/cmd
        id: get_job_deployment
        runner: "{{ $.params.runner }}"
        args:
          - get
          - jobs
          - '{{ $.params.job_name }}'
          - -o
          - yaml
          - -n
          - '{{ $.params.namespace }}'
      - name: us-docker.pkg.dev/stackpulse/public/kubectl/delete
        runner: "{{ $.params.runner }}"
        id: kubectl_delete
        env:
          RESOURCE_TYPE: job
          RESOURCES_NAMES: "{{ $.params.job_name }}"
      - name: us-docker.pkg.dev/stackpulse/public/utils/replace-string
        id: remove_controller_uid
        env:
          ORIGINAL_BASE64_STRING: "{{ b64enc $.get_job_deployment.output }}"
          SUB_STR_SRC: " +?controller-uid: .*\n"
          SUB_STR_DEST: ""
          REGEX: "True"
      - name: us-docker.pkg.dev/stackpulse/public/kubectl/apply-file
        id: kubectl_apply_job_deployment
        runner: "{{ $.params.runner }}"
        env:
          APPLY_CONTENT: "{{ $.remove_controller_uid.output }}"
      - name: us-docker.pkg.dev/stackpulse/public/slack/message/dynamic
        id: slack_send_dynamic_message
        envFrom:
          integrationRef: "{{ $.params.slack_integration }}"
        env:
          RECIPIENTS: "{{ $.params.recipient }}"
          MESSAGE_TEXT: Succesfully initiated a rerun of the job {{ $.params.job_name }}!
          SP_REDIRECT_URL: "{{ $.metadata.executionUrl }}"
