apiVersion: stackpulse.io/v1
kind: Playbook
metadata:
  name: linux-diagnostics
  description: This playbook fetch data regarding cpu usage, memory and storage for given machine
parameters:
  - name: username
    type: var
    description: username for remote access machine
  - name: hostname
    type: var
    description: hostname for the remote machine
  - name: sshKey
    type: secret
    description: private key access the remote machine via ssh
  - name: SlackIntegration
    type: integration
    description: Slack integration name
    options:
      integration_type: slack
  - name: slackChannel
    type: var
    description: Destination slack channel
  - name: runnerName
    type: var
    description: "SPD runner name which has ssh access to the destination machine"
steps:

  # Retrieve top running processes, sorted by memory consumption
  - name: us-docker.pkg.dev/stackpulse/public/ssh/command
    id: process_stat_step
    runner: '{{ $.params.runnerName }}'
    env:
      COMMAND: ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -11
      USERNAME: '{{ $.params.username }}'
      HOSTNAME: '{{ $.params.hostname }}'
      PRIVATE_KEY: '{{ secret $.params.sshKey }}'
  
  # Send snippet message of the top memory consuming processes to the slack channel
  - name: us-docker.pkg.dev/stackpulse/public/slack/message/snippet
    id: send_ps_output
    env:
      SP_REDIRECT_URL: '{{ $.metadata.executionUrl }}'
      CONTENT: "{{ $.process_stat_step.output }}"
      INITIAL_COMMENT: Information about a selection of the active proccess for the host {{ $.params.hostname }}
      RECIPIENTS: "{{ $.params.slackChannel }}"
      TITLE: ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -11
    envFrom:
      integrationRef: '{{ $.params.SlackIntegration }}'

  # Retrieve data about storage partions
  - name: us-docker.pkg.dev/stackpulse/public/ssh/command
    id: storage_step
    runner: '{{ $.params.runnerName }}'
    env:
      COMMAND: df -h
      USERNAME: '{{ $.params.username }}'
      HOSTNAME: '{{ $.params.hostname }}'
      PRIVATE_KEY: '{{ secret $.params.sshKey }}'
      
  # Send snippet message of the data about storage partions to the slack channel
  - name: us-docker.pkg.dev/stackpulse/public/slack/message/snippet
    id: send_df_output
    env:
      SP_REDIRECT_URL: '{{ $.metadata.executionUrl }}'
      CONTENT: "{{ $.storage_step.output }}"
      INITIAL_COMMENT: Information about machine storage devices {{ $.params.hostname }}
      RECIPIENTS: "{{ $.params.slackChannel }}"
      TITLE: df -h
    envFrom:
      integrationRef: '{{ $.params.SlackIntegration }}'

  # Retrieve virtual memory statistics data
  - name: us-docker.pkg.dev/stackpulse/public/ssh/command
    id: vmstat_step
    runner: '{{ $.params.runnerName }}'
    env:
      COMMAND: vmstat
      USERNAME: '{{ $.params.username }}'
      HOSTNAME: '{{ $.params.hostname }}'
      PRIVATE_KEY: '{{ secret $.params.sshKey }}'

  # Send snippet message of virtual memory statistics data to the slack channel
  - name: us-docker.pkg.dev/stackpulse/public/slack/message/snippet
    id: send_vmstat_output
    env:
      SP_REDIRECT_URL: '{{ $.metadata.executionUrl }}'
      CONTENT: "{{ $.vmstat_step.output }}"
      INITIAL_COMMENT: Information about processes, memory, paging, block IO, traps, and cpu activity for the host {{ $.params.hostname }}
      RECIPIENTS: "{{ $.params.slackChannel }}"
      TITLE: vmstat
    envFrom:
      integrationRef: '{{ $.params.SlackIntegration }}'